# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [4]:
np.zeros(10,dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

#### Create an array of 10 ones

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [7]:
np.array([5 for var in range(0,10)])

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [9]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [10]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
a=np.arange(0,9)
a.reshape(3,3,order="F")

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

#### Create a 3x3 identity matrix

In [15]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [25]:
np.random.randint(4,5)

4

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [31]:
np.random.randn(25)

array([ 0.10226081, -1.04883526,  0.40063789,  0.38876405, -0.93742274,
       -1.21221216, -0.04427668, -0.3776721 ,  0.26102461,  0.43693079,
        1.30099623,  0.71434547, -1.49157085, -1.2750087 ,  0.51864682,
        0.53040231, -1.11935546, -0.16424194,  1.01117408,  1.52126175,
        1.5526251 ,  1.09411929, -0.03895497,  0.02382932, -0.46234257])

#### Create the following matrix:

TypeError: 'float' object cannot be interpreted as an integer

#### Create an array of 20 linearly spaced points between 0 and 1:

In [43]:
np.random.uniform(0,1,20)

array([0.48580641, 0.41507084, 0.63523684, 0.0574716 , 0.44430274,
       0.97824088, 0.18003715, 0.11851624, 0.65576713, 0.62983201,
       0.96660894, 0.25002357, 0.14940601, 0.38836013, 0.59152449,
       0.4501863 , 0.32045373, 0.20456045, 0.56921456, 0.10439476])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [45]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [46]:
mat[2:,[1,2,3,4]]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [48]:
mat[3][4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [49]:
mat[0:3,[1]]

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [50]:
mat[4]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [51]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [52]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [53]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [94]:
c=[]
for col in range(0,5):
    
    a=mat[:,[col]]
    b=np.sum(a)
    c.append(b)
c

[55, 60, 65, 70, 75]

# Great Job!