In [1]:
import numpy as np


In [2]:
l=[1,2,3,4,5,6,7,8,9,10]

In [5]:
y=np.array(l).reshape((-1,2),order='F')

In [6]:
y

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [7]:
from numpy import random

In [8]:
random.random()

0.02718851956709789

In [11]:
random.random((5,4)) #uniform distribution 0-1

array([[0.4552376 , 0.7195314 , 0.51054272, 0.32620854],
       [0.81752168, 0.90977189, 0.92412113, 0.28560451],
       [0.33709743, 0.47860183, 0.59403589, 0.8354771 ],
       [0.31647962, 0.0074013 , 0.85839771, 0.53900842],
       [0.0510862 , 0.18571639, 0.58335328, 0.01790501]])

In [12]:
a=random.randn(10)

In [13]:
np.mean(a)

0.1688264106402461

In [14]:
np.median(a)

0.20145527742292682

In [15]:
np.mode(a)

AttributeError: module 'numpy' has no attribute 'mode'

In [16]:
import statistics as stat


In [17]:
dir(stat)

['Decimal',
 'Fraction',
 'StatisticsError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_coerce',
 '_convert',
 '_counts',
 '_exact_ratio',
 '_fail_neg',
 '_find_lteq',
 '_find_rteq',
 '_isfinite',
 '_ss',
 '_sum',
 'bisect_left',
 'bisect_right',
 'chain',
 'collections',
 'decimal',
 'groupby',
 'harmonic_mean',
 'math',
 'mean',
 'median',
 'median_grouped',
 'median_high',
 'median_low',
 'mode',
 'numbers',
 'pstdev',
 'pvariance',
 'stdev',
 'variance']

In [18]:
stat.stdev(a)

0.7820566657721801

this is the sample of x_bar is $ \bar{x}$ using latex

% % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % $$\frac {\sum_{i=1}^N x_i} /////.]
[]
=']]



In [19]:
a=np.arange(1,101).reshape((10,10))

In [20]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [21]:
import pandas as pd

In [27]:
df=pd.DataFrame(a,columns=["a","b","c","d","e","f","g","h","i","j"])

In [28]:
df

a   b   c   d   e   f   g   h   i    j
0   1   2   3   4   5   6   7   8   9   10
1  11  12  13  14  15  16  17  18  19   20
2  21  22  23  24  25  26  27  28  29   30
3  31  32  33  34  35  36  37  38  39   40
4  41  42  43  44  45  46  47  48  49   50
5  51  52  53  54  55  56  57  58  59   60
6  61  62  63  64  65  66  67  68  69   70
7  71  72  73  74  75  76  77  78  79   80
8  81  82  83  84  85  86  87  88  89   90
9  91  92  93  94  95  96  97  98  99  100

In [30]:
import matplotlib.pyplot as plt
%matplotlib inline

In [1]:
#CREATING NUMPY ARRAYS

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5,6,7])

In [4]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
a.ndim

1

In [6]:
a.size

7

In [7]:
a.shape

(7,)

In [8]:
a=np.array([1,2,3,4,5,7],dtype=complex,ndmin=2)

In [9]:
a

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 7.+0.j]])

In [10]:
a.ndim

2

In [11]:
a.shape

(1, 6)

In [12]:
a.size

6

In [13]:
#ARRAY ATTRIBUTES

In [14]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5]])
a

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [15]:
a.shape

(2, 5)

In [16]:
a.shape=(5,2)

In [17]:
a

array([[1, 2],
       [3, 4],
       [5, 1],
       [2, 3],
       [4, 5]])

In [18]:
b=a.reshape(2,5)

In [19]:
b

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [21]:
a=np.arange(24)
a
a.ndim

1

In [22]:
b=a.reshape(2,4,3)

In [23]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [31]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]],dtype=np.int8)

In [32]:
a.itemsize

1

In [35]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [3]:
import numpy as np
a=[[1,2,3],[4,5,2]]
b=[[1],[2],[3]]

In [6]:
a1=np.array(a)
a2=np.array(b)

In [7]:
a1

array([[1, 2, 3],
       [4, 5, 2]])

In [8]:
a2

array([[1],
       [2],
       [3]])

In [10]:
a1@a2

array([[14],
       [20]])

In [11]:
x=np.arange(1,101)

In [12]:
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [13]:
x.ndim

1

In [14]:
x.shape

(100,)

In [16]:
x.size

100

In [18]:
x.reshape(20,5)

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [19]:
l=[ '1' for var in range(32)]
l="".join(l)

In [20]:
l

'11111111111111111111111111111111'

In [22]:
int(l,2)

4294967295

In [23]:
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [28]:
ord('A')

65

In [29]:
ord('Z')

90

In [27]:
for var in range(65,91):
    try:
        x.reshape((10,10),order=chr(var))
        print(chr(var))
    except:
        continue

A
C
F


In [35]:
x.reshape((10,10),order='F')

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [43]:
s=[1,2,3,4,5,6,7,8,9,12,12,3,4,6,8,5,3,12,0,45]

In [44]:
s

[1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 12, 3, 4, 6, 8, 5, 3, 12, 0, 45]

In [48]:
a=np.array(s)

In [49]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 12, 12,  3,  4,  6,  8,  5,  3,
       12,  0, 45])

In [53]:
a.reshape((5,4),order='F')

array([[ 1,  6, 12,  5],
       [ 2,  7,  3,  3],
       [ 3,  8,  4, 12],
       [ 4,  9,  6,  0],
       [ 5, 12,  8, 45]])

In [60]:
a=np.arange(1,101)

In [61]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [65]:
a.reshape((10,-1),order='F')

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [66]:
from numpy import random

In [69]:
a=random.random(100)

In [70]:
b=random.randn(100)

In [74]:
np.mean(a)

0.49335947000189406

In [75]:
np.median(a)

0.48941807149085026

In [77]:
np.mean(b)

0.11246425358264785

In [78]:
np.median(b)

0.2574926589841562

In [79]:
import statistics as stat

In [80]:
print(dir(stat))

['Decimal', 'Fraction', 'StatisticsError', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_coerce', '_convert', '_counts', '_exact_ratio', '_fail_neg', '_find_lteq', '_find_rteq', '_isfinite', '_ss', '_sum', 'bisect_left', 'bisect_right', 'chain', 'collections', 'decimal', 'groupby', 'harmonic_mean', 'math', 'mean', 'median', 'median_grouped', 'median_high', 'median_low', 'mode', 'numbers', 'pstdev', 'pvariance', 'stdev', 'variance']


In [81]:
stat.mean(a)

0.49335947000189406

In [82]:
stat.median(a)

0.48941807149085026

In [83]:
stat.mode(a)

StatisticsError: no unique mode; found 100 equally common values

In [84]:
stat.stdev(a)

0.274921960619019

#latex-->language for mathematical formulas
#sympy-->symbolic python
$$\sum$$
$$\pi$$
$$\frac {x} {y}$$
$$\sigma$$
$$\forall$$
$$x_i$$

$$\text{mean=}  \frac {\sum_{i=1} ^N x_i }{N}$$
$$\sigma^2=\frac {\sum_{i=1} ^N (x-\bar{x})^2} {N}$$
$$\sigma =\sqrt{\sigma}$$

In [85]:
import pandas as pd

In [86]:
print(dir(pd))

['Categorical', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'ExcelFile', 'ExcelWriter', 'Expr', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int64Index', 'Interval', 'IntervalIndex', 'MultiIndex', 'NaT', 'Panel', 'Period', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseArray', 'SparseDataFrame', 'SparseSeries', 'Term', 'TimeGrouper', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt64Index', 'WidePanel', '_DeprecatedModule', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_hashtable', '_lib', '_libs', '_np_version_under1p10', '_np_version_under1p11', '_np_version_under1p12', '_np_version_under1p13', '_np_version_under1p14', '_np_version_under1p15', '_tslib', '_version', 'api', 'bdate_range', 'compat', 'concat', 'core', 'crosstab', 'cut', 'date_range', 'datetime', 'datetools', 'describe_option', 'errors', 'eval', 'factorize', 'get_dummies', 'get_opt

In [104]:
a=np.arange(1,101)

In [105]:
b=a.reshape((10,10))

In [106]:
df=pd.DataFrame(b,columns=['a','b','c','d','e','f','g','h','i','j'])

In [107]:
df

a   b   c   d   e   f   g   h   i    j
0   1   2   3   4   5   6   7   8   9   10
1  11  12  13  14  15  16  17  18  19   20
2  21  22  23  24  25  26  27  28  29   30
3  31  32  33  34  35  36  37  38  39   40
4  41  42  43  44  45  46  47  48  49   50
5  51  52  53  54  55  56  57  58  59   60
6  61  62  63  64  65  66  67  68  69   70
7  71  72  73  74  75  76  77  78  79   80
8  81  82  83  84  85  86  87  88  89   90
9  91  92  93  94  95  96  97  98  99  100

In [109]:
df.describe()

a          b          c          d          e          f  \
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
mean   46.000000  47.000000  48.000000  49.000000  50.000000  51.000000   
std    30.276504  30.276504  30.276504  30.276504  30.276504  30.276504   
min     1.000000   2.000000   3.000000   4.000000   5.000000   6.000000   
25%    23.500000  24.500000  25.500000  26.500000  27.500000  28.500000   
50%    46.000000  47.000000  48.000000  49.000000  50.000000  51.000000   
75%    68.500000  69.500000  70.500000  71.500000  72.500000  73.500000   
max    91.000000  92.000000  93.000000  94.000000  95.000000  96.000000   

               g          h          i           j  
count  10.000000  10.000000  10.000000   10.000000  
mean   52.000000  53.000000  54.000000   55.000000  
std    30.276504  30.276504  30.276504   30.276504  
min     7.000000   8.000000   9.000000   10.000000  
25%    29.500000  30.500000  31.500000   32.500000  
50%    52.000000  53.000000  54.000000   55.000000  
75%    74.500000  75.500000  76.500000   77.500000  
max    97.000000  98.000000  99.000000  100.000000

In [111]:
a=random.randint(20,50,50).reshape(5,2,5)

In [112]:
a

array([[[21, 45, 28, 29, 23],
        [39, 40, 43, 37, 25]],

       [[42, 27, 31, 43, 46],
        [34, 41, 46, 47, 34]],

       [[21, 49, 37, 39, 30],
        [40, 31, 32, 46, 47]],

       [[35, 41, 42, 46, 22],
        [20, 41, 25, 29, 29]],

       [[41, 43, 20, 22, 34],
        [37, 41, 28, 25, 39]]])

In [113]:
a.size

50

In [114]:
a.shape

(5, 2, 5)

In [115]:
a.ndim

3

In [116]:
import matplotlib.pyplot as plt
%matplotlib inline

FileNotFoundError: [Errno 2] No such file or directory: 'one.jpg'